export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpeg",
    username: "Massinissa Ait salah",
  },
  {
    id: 2,
    profilePicture: "person/2.jpeg",
    username: "Aissa Ait salah",
  },

  {
    id: 3,
    profilePicture: "person/3.jpeg",
    username: "Yazid Ait salah",
  },

  {
    id: 4,
    profilePicture: "person/4.jpeg",
    username: "Siham Ait salah",
  },
  {
    id: 5,
    profilePicture: "person/5.jpeg",
    username: "Khellaf Ait salah",
  },
  {
    id: 6,
    profilePicture: "person/6.jpeg",
    username: "Heddouche Zellal",
  },
  {
    id: 7,
    profilePicture: "person/7.jpeg",
    username: "Khellaf Tellili",
  },
  {
    id: 8,
    profilePicture: "person/8.jpeg",
    username: "Chameseddine Addour",
  },
  {
    id: 9,
    profilePicture: "person/9.jpeg",
    username: "Iflisen Zahir",
  },
  {
    id: 10,
    profilePicture: "person/10.jpeg",
    username: "Mohand ukassi",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "J'aime pour tous, est vous la?",
    photo: "post/1.jpeg",
    date: "5 min Avant",
    userId: 1,
    like: 32,
    comment: 25,
  },
  {
    id: 2,
    desc: "Je viens de m'inscrire sur ce réseaux.",
    photo: "post/2.jpeg",
    date: "15 min Avant",
    userId: 2,
    like: 5,
    comment: 44,
  },
  {
    id: 3,
    desc: "Regarder comment c'est jolie!",
    photo: "post/3.jpeg",
    date: "1 heure Avant",
    userId: 3,
    like: 8,
    comment: 1,
  },
  {
    id: 4,
    desc: "c'est la féte yupppii.",
    photo: "post/4.jpeg",
    date: "2 jours Avant",
    userId: 4,
    like: 3,
    comment: 47,
  },
  {
    id: 5,
    desc: "je suis triste ces derniers jours.",
    photo: "post/5.jpeg",
    date: "15 jours Avant",
    userId: 5,
    like: 100,
    comment: 200,
  },
  {
    id: 6,
    desc: "je vois pas l'intéret de ce montrer",
    photo: "post/6.jpeg",
    date: "1 min Avant",
    userId: 6,
    like: 12,
    comment: 0,
  },
  {
    id: 7,
    photo: "post/7.jpeg",
    date: "1 mois Avant",
    userId: 7,
    like: 555,
    comment: 0,
  },
  {
    id: 8,
    desc: "aimer aus autres ce que vous aimer a vos mémes",
    photo: "post/8.jpeg",
    date: "2 ans Avant",
    userId: 8,
    like: 1000,
    comment: 150,
  },
  {
    id: 9,
    desc: "ne vous laissez pas emportez par la foule",
    photo: "post/9.jpeg",
    date: "5 min Avant",
    userId: 9,
    like: 12,
    comment: 0,
  },
  {
    id: 10,
    photo: "post/10.jpeg",
    date: "5 min Avant",
    userId: 10,
    like: 12,
    comment: 0,
  },
];
